name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Check install of Python, pre-commit
      run: |
        ./Utilities/GitSetup/setup-precommit
        git config hooks.SetupForDevelopment 99
        git config user.email "you@example.com"
        git config user.name "Your Name"
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: pre-commit/action@v3.0.1
